[project]
name = "stocker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.14",
    "lightgbm>=4.6.0",
    "pandas>=2.3.1",
    "pyside6>=6.9.1",
    "requests>=2.32.4",
    "scikit-learn>=1.7.1",
    "ta-lib",
    "torch>=2.7.1",
]

[[tool.uv.index]]
url = "http://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[tool.uv.sources]
ta-lib = { path = "ta_lib-0.6.4-cp313-cp313-win_amd64.whl" }
